ZONE ?= us-west1-a

.PHONY: login project zone configuration cluster

login: configuration
	gcloud auth login --no-launch-browser

project:
	-gcloud config set project $(PROJECT)

zone:
	gcloud config set compute/zone $(ZONE)

configuration: project zone
	-gcloud config configurations create $(PROJECT)
